### ISSUE TITLE
sqlite3.OperationalError: no such table: requests

### ISSUE THREAD

**Issue by edartcode** [xmi666/trape#4]
sqlite3.OperationalError: no such table: requests

**Comment by xmi666** [comment]
Hm, i can't reproduce the error you get. Could you be more specific about it? What did you do before you got the message?

**Comment by edartcode** [comment]
thank you for reply me. This issue has been resolved.  I delete the db.file and restart it

**Comment by xmi666** [comment]
Thats nice. Cheers and have a great day.
